experiment_name: test
batch_size: 16
num_mols: 32
max_size: 20

guidance_mode: inverse
guidance_strength: 0.3
min_gui_scale: 0.125
scale_mode: fractional
bond_guidance_strength: 0.0

default_sigma: 1.0 # sigma for all elements, can be overridden by element_sigmas
element_sigmas:
  7: 1.3805698509951765
  16: 1.3930321526384768

sigma_schedule: constant
constant_sigma_value: 1.546052043589046

# IS parameters
importance_sampling_freq: 100
inverse_temperature: 0.005
mini_batch: 4
