experiment_name: test_no_h_in_ref
batch_size: 16
num_mols: 32
max_size: 20
keep_h_in_ref_atoms: false

guidance_mode: inverse
guidance_strength: 0.45
min_gui_scale: 0.15
scale_mode: fractional
bond_guidance_strength: 0.0

default_sigma: 1.0 # sigma for all elements, can be overridden by element_sigmas
element_sigmas:
  7: 1.0
  16: 1.3

sigma_schedule: matching
constant_sigma_value: 0.7

# IS parameters
importance_sampling_freq: 50
inverse_temperature: 0.006
mini_batch: 4

results_dir: results