batch_size: 32
default_sigma: 1.
# element_sigmas:
#   7: 1.2
#   16: 1.2
experiment_name: test
guidance_strength: 0.25
bond_guidance_strength: 0.0000
num_mols: 8
num_replicas: 1
scale_mode: absolute
