batch_size: 64
default_sigma: 0.3108293369371529
element_sigmas:
  7: 0.25
  16: 0.25
experiment_name: test
guidance_strength: 0.20
bond_guidance_strength: 0.0000
num_mols: 512
num_replicas: 1
scale_mode: absolute
