experiment_name: direct_sum_gui_is_low_t
batch_size: 128
num_mols: 5120
max_size: 20
keep_h_in_ref_atoms: true

guidance_mode: direct
guidance_strength: 0.080
min_gui_scale: 0.015
scale_mode: fractional
bond_guidance_strength: 0.0

default_sigma: 1.0 # sigma for all elements, can be overridden by element_sigmas
element_sigmas:
  7: 1.4
  16: 1.4

sigma_schedule: matching
constant_sigma_value: 1.4

# IS parameters
importance_sampling_freq: 50
inverse_temperature: 0.06
mini_batch: 4

results_dir: ./results_production